[package]
name = "blox-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
blox-parser = {workspace = true}
clap = { version = "4.5.32", features = ["derive"] }
miette = { version = "7.5.0", features = ["fancy"] }
thiserror = "2.0.12"
